name: Check Website Uptime
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  check-uptime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check website status
        run: |
          curl --output /dev/null --silent --head --fail https://leechihh.github.io/
          if [ $? -ne 0 ]; then
            echo "Website is down"
          else
            echo "Website is up"
          fi